### ISSUE TITLE
Doubt regarding evaluation of FVD values

### ISSUE THREAD

**Issue by ry85** [edouardelasalles/srvp#11]
Hi,

Thanks for sharing the codes of your paper.

I was going through the test.py script, there while calculating fvd you had concatenated both conditioning frames and the generated frames to calculate the fvd. Shouldn't it only be the generated frames we should use?

Thanks

**Comment by White-Link** [comment]
Hi, thanks for your interest in our work!

We computed FVD using this concatenation in order to take into account conditioning frames when computing the score in accordance with the prediction task. Indeed, if FVD were computed using generated frames only, the resulting score would not assess the temporal consistency of the predictions with respect to the conditioning frames. More formally, the current computation method compares joint distributions p(x)p(x'|x) where x are conditioning frames and x' are either ground truths or predictions.

The reported FVD for all considered baselines is computed in the exact same manner, so our comparative evaluation remains correct.

We are closing this issue for now as we addressed your interrogation, please let us know whether you have any other question!
