### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by sb93** [edouardelasalles/srvp#12]
Hi!

Thank you for sharing your code for this work. I am getting the following error when I try to train on Moving MNIST (stochastic) :
![srvp_err](https://user-images.githubusercontent.com/14817792/126851512-13139fea-1596-40f0-b010-2b6e97f6ead4.png)

Could you kindly point out the issue? Thank you.

**Comment by White-Link** [comment]
Hi, thank you for your interest in our work!

We do not encounter this error when training the model on our side. Could you please provide more information to help us determining the problem? In particular, what is the command that you executed and what is the version of PyTorch that you are using?

Since the issue seems to lie in multiprocessing worker management, you may try to set `--n_workers 0`, which disables this optimization but might make training slower.
