### ISSUE TITLE
Reproducing results on Stochastic MNIST

### ISSUE THREAD

**Issue by kaanakan** [edouardelasalles/srvp#9]
Hi,

I was trying to reproduce results from the paper on stochastic moving MNIST dataset. The results I got when I run the code with the instructions on README file and your pretrained model:

Results:
psnr 16.066757 +/- 0.06360093271710796
ssim 0.75027704 +/- 0.0019019813119048063
lpips 0.13383576 +/- 0.0010925805679736199

However, the results are not matching with the paper. I assume "ours" is the shared model. Results for PSNR and SSIM on paper:
Ours 16.93 ± 0.07 0.7799 ± 0.0020

Am I doing something wrong with the code?

Thanks a lot.

Edit: I forgot to mention that I created the test set with command you shared on the Readme

**Comment by White-Link** [comment]
Hi, thank you for reporting this issue!

After investigating the matter, we found that our instructions in the `README.md` file were incorrect regarding the creation of the Moving MNIST dataset and the testing script options for stochastic Moving MNIST.

In particular, as indicated in our article, the total number of frames (including conditioning ones) to use during testing for stochastic Moving MNIST should be 25, and not 30 as originally given in the testing command. You will obtain the results reported in the article now that this issue is fixed.

Please let us know if you encounter any other problem.
